title: Chris Boakes
email: chris@chrisboakes.com
description: > # this means to ignore newlines until "baseurl:"
  Code and development blog of London based front-end web developer Chris Boakes
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
source: src
destination: public

# Links
permalink: /:title/
collections:
    category:
        output: true
    bios:
        output: false
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
